// _                           _
// ___ _   _  ___| |_ ___ _   _    __ _ _   _| |_ ___   __ _  ___ _ __
// / __| | | |/ _ \ __/ __| | | |  / _` | | | | __/ _ \ / _` |/ _ \ '_ \
// | (__| |_| |  __/ |_\__ \ |_| | | (_| | |_| | || (_) | (_| |  __/ | | |
// \___|\__,_|\___|\__|___/\__, |  \__,_|\__,_|\__\___/ \__, |\___|_| |_|
//                     |___/                        |___/
// AUTOGENERATED from model.cue
// do not edit
//

export enum TextMode {
  Html = 'html',
  Markdown = 'markdown',
}

export interface Options {
  mode: TextMode;
  content: string;
}

export const defaultOptions: Options = {
  mode: TextMode.Markdown,
  content: `# Title

For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)`,
};

export const modelVersion = 1; // numeric incrementer
export const modelHash = 'abcd'; // includes changes to defaults?
